language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
env:
    - MATRIX_EVAL = "CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir build
    - cd build 
    - cmake ../
script:
    - cd build
    - make
after_script:
    - cd build
    - ./Test
